### PR TITLE
More robust status command

### LINKED ISSUE #37: Status command fails on timeout
If you run the `status` command when a server has been added (via `add server`) but not yet connected, the `show` command takes a long time to timeout and doesn't show any info about the rest of the network that is connected.

### PR DESCRIPTION
**Pull request by Aptimex**
Fixes #37 

Adds a 3s timeout when trying to get info from a server via the `status` command, and still shows data about the rest of the working network instead of immediately exiting.

### CODE REVIEW

File: src/api/api.go [hunk 1]
```diff
@@ -27,7 +28,7 @@ type request struct {
 
 // MakeRequest attempts to send an API query to the Wiretap server.
 func makeRequest(req request) ([]byte, error) {
-	client := &http.Client{}
+	client := &http.Client{Timeout: 3 * time.Second}
```
Comment (luker983) [inline src/api/api.go:31]: Yup, should've had this from the beginning. Thanks.

File: src/cmd/status.go [hunk 2]
```diff
@@ -77,11 +78,20 @@ func (c statusCmdConfig) Run() {
...
 		relayConfig, e2eeConfig, err := api.ServerInfo(netip.AddrPortFrom(ep.GetApiAddr(), uint16(ApiPort)))
-		check("failed to fetch node's configuration as peer", err)
-		nodes[relayConfig.GetPublicKey()] = Node{
-			peerConfig:  ep,
-			relayConfig: relayConfig,
-			e2eeConfig:  e2eeConfig,
+		if err != nil {
+			message := "failed to fetch node's configuration as peer"
+			log.Printf("%s: %v", message, err)
+			nodes["TIMEOUT"] = Node{
```
Comment (luker983) [inline src/cmd/status.go:84]: This will be overridden by other failed nodes (and isn't necessarily caused by a timeout). 

Just an idea, but what do you think about adding a new field in the `Node` struct so the errors can be saved along the corresponding nodes? This way we don't lose info and can potentially display it in the visualization down the road.

File: src/cmd/status.go [hunk 3]
```diff
@@ -111,8 +121,8 @@ func (c statusCmdConfig) Run() {
 	// Use node tree to build diagram tree.
 	t.AddChild(tree.NodeString(fmt.Sprintf(`client
 
-  relay: %v... 
-   e2ee: %v... 
+  relay: %v...
```
Comment (luker983) [inline src/cmd/status.go:124]: I believe the trailing whitespace here was intentional to give the boxes some padding. Did you mean to remove the spaces or is it something like a side effect of editor/linter?

**Review by luker983 — COMMENTED** [review]
Makes sense to me! Could you please include a side-by-side of the behavior from the Issue and how it looks now as fixed by this PR?

File: src/api/api.go
Comment (luker983) [inline src/api/api.go:1]: This is odd, file permissions on the changed files went from `644` → `755`. From some quick searching this may be a side effect of using WSL if you didn't explicitly change them

File: src/cmd/status.go (hunk 2 above)
Comment (Aptimex) [reply src/cmd/status.go:84]: Yeah this was just my quickest solution to get the rest of the connected network to display. It would definitely be preferable to actually save failure info specific to the node and display it nicely.

File: src/cmd/status.go (hunk 3 above)
Comment (Aptimex) [reply src/cmd/status.go:124]: Not intentional, editor did it automatically.

File: src/api/api.go
Comment (Aptimex) [reply src/api/api.go:1]: Yup, probably WSL being weird. I didn't mean to change that.

**Comment by Aptimex** [comment]
> Makes sense to me! Could you please include a side-by-side of the behavior from the Issue and how it looks now as fixed by this PR?

Before (one server setup but not connected):
```
./wiretap status
2024/07/17 21:25:48 failed to fetch node's configuration as peer: Get "http://::2:80/serverinfo?": dial tcp [::2]:80: connect: network is unreachable
```

After:
```
2024/07/17 21:25:34 failed to fetch node's configuration as peer: Get "http://::2:80/serverinfo?": dial tcp [::2]:80: connect: network is unreachable

╭────────────────────────╮ 
│ Wiretap Network Status │                                                                                                                                                                                                                  
╰────────────┬───────────╯                                                                                                                                                                                                                  
             │                                                                                                                                                                                                                              
  ╭──────────┴──────────╮                                                                                                                                                                                                                   
  │client               │                                                                                                                                                                                                                   
  │                     │                                                                                                                                                                                                                   
  │  relay: EcX0bRmF... │                                                                                                                                                                                                                   
  │   e2ee: N7Fkb6rq... │                                                                                                                                                                                                                   
  │                     │                                                                                                                                                                                                                   
  ╰─────────────────────╯
```

**Comment by Aptimex** [comment]
Added a second commit to undo the whitespace and file permission changes.

File: src/cmd/status.go (hunk 2 above)
Comment (luker983) [reply src/cmd/status.go:84]: Gotcha. Does this line need to exist at all then?

**Comment by luker983** [comment]
I don't have write access to this repository anymore, but I approve!

File: src/cmd/status.go (hunk 2 above)
Comment (Aptimex) [reply src/cmd/status.go:84]: Annoyingly, yes, Can't remember exactly where, but without adding some kind of placeholder entry here it was causing another crash somewhere else.

Comment (luker983) [reply src/cmd/status.go:84]: I commented it out and it seems to work just fine.

The only place `nodes` is used is in the `findChildren` function and is always indexed by public key so it should have no effect.

Comment (Aptimex) [reply src/cmd/status.go]: Yup, must have been a different issue that I accidentally solved while adding that. Added another commit to take that out.

**Review by Segudmu — APPROVED** [review]
